/*******************************************************************************
* File Name: secure_keys.h
*
* Description: This file contains configuration parameters for the secure HTTP
* client and the client security keys such as server certificate, private key,
* and the root CA (certificate authority) to trust the server.
*
* Related Document: See README.md
********************************************************************************
* (c) 2024-2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
* This software, associated documentation and materials ("Software") is owned by
* Infineon Technologies AG or one of its affiliates ("Infineon") and is protected
* by and subject to worldwide patent protection, worldwide copyright laws, and
* international treaty provisions. Therefore, you may use this Software only as
* provided in the license agreement accompanying the software package from which
* you obtained this Software. If no license agreement applies, then any use,
* reproduction, modification, translation, or compilation of this Software is
* prohibited without the express written permission of Infineon.
* Disclaimer: UNLESS OTHERWISE EXPRESSLY AGREED WITH INFINEON, THIS SOFTWARE
* IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
* BUT NOT LIMITED TO, ALL WARRANTIES OF NON-INFRINGEMENT OF THIRD-PARTY RIGHTS AND
* IMPLIED WARRANTIES SUCH AS WARRANTIES OF FITNESS FOR A SPECIFIC USE/PURPOSE OR
* MERCHANTABILITY. Infineon reserves the right to make changes to the Software
* without notice. You are responsible for properly designing, programming, and
* testing the functionality and safety of your intended application of the
* Software, as well as complying with any legal requirements related to its
* use. Infineon does not guarantee that the Software will be free from intrusion,
* data theft or loss, or other breaches ("Security Breaches"), and Infineon
* shall have no liability arising out of any Security Breaches. Unless otherwise
* explicitly approved by Infineon, the Software may not be used in any application
* where a failure of the Product or any consequences of the use thereof can
* reasonably be expected to result in personal injury.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef SECURE_KEYS_H_
#define SECURE_KEYS_H_

/* HTTPS server certificate. Copy from the HTTPS server certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keyCLIENT_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIIB8TCCAZcCFFF6yaKuj0xHCI+LCVgSf6IG9zMWMAoGCCqGSM49BAMCMHsxCzAJ\n"\
"BgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJlbmdhbHVy\n"\
"dTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0VuZ2luZWVyaW5nMSEwHwYDVQQDDBht\n"\
"eXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwHhcNMjUxMjA2MDcyODEzWhcNMjgwOTAx\n"\
"MDcyODEzWjB7MQswCQYDVQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYD\n"\
"VQQHDAlCZW5nYWx1cnUxCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmlu\n"\
"ZzEhMB8GA1UEAwwYbXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMFkwEwYHKoZIzj0C\n"\
"AQYIKoZIzj0DAQcDQgAE4KDV2ntBVM60Mk3K19a9ayTsSzuV5P2+GwMj0UB3paJS\n"\
"ZhjdDpCPtpPvDD33aidZaaoR7aE58qrct3IyeHTRVDAKBggqhkjOPQQDAgNIADBF\n"\
"AiEAwrg8qGtRW0eHYCxJstIj3LA5PVpJeOsLnlRwVsl+ELYCIBPBmPhClmW5Jomo\n"\
"LU4duZh+LwZL/nQu/2Zvs+cH8N9j\n"\
"-----END CERTIFICATE-----\n"

/* Private key of the HTTPS server. Copy from the HTTPS server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keyCLIENT_PRIVATE_KEY_PEM \
"-----BEGIN EC PRIVATE KEY-----\n"\
"MHcCAQEEICVIgNfdowOJ/dBPpSoo0DdgnDqRFSanVTSX++TQqcIkoAoGCCqGSM49\n"\
"AwEHoUQDQgAE4KDV2ntBVM60Mk3K19a9ayTsSzuV5P2+GwMj0UB3paJSZhjdDpCP\n"\
"tpPvDD33aidZaaoR7aE58qrct3IyeHTRVA==\n"\
"-----END EC PRIVATE KEY-----\n"

/* HTTPS client certificate. In this example this is the RootCA
 * certificate so as to verify the HTTPS client's identity.
 */
#define keySERVER_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIICSzCCAfGgAwIBAgIUIcI7drNyJZDsqhOpl2rzR0chrO8wCgYIKoZIzj0EAwIw\n"\
"ezELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJQmVu\n"\
"Z2FsdXJ1MQswCQYDVQQKDAJDWTEUMBIGA1UECwwLRW5naW5lZXJpbmcxITAfBgNV\n"\
"BAMMGG15c2VjdXJlaHR0cHNlcnZlci5sb2NhbDAeFw0yNTEyMDYwNzI4MTNaFw0y\n"\
"NjAxMDUwNzI4MTNaMHsxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2Ex\n"\
"EjAQBgNVBAcMCUJlbmdhbHVydTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0VuZ2lu\n"\
"ZWVyaW5nMSEwHwYDVQQDDBhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwWTATBgcq\n"\
"hkjOPQIBBggqhkjOPQMBBwNCAASo7/6p9MTzk57FWrkVdvMCxJbQTAhSx3wMpdhm\n"\
"iqE0umSNUTaT3a5V+7oGrczO3YA3Htkn1IIDPaaTWzfZ8vrdo1MwUTAdBgNVHQ4E\n"\
"FgQU/Xm2c3jfKKnuQ5hVGyUn+C9RkvIwHwYDVR0jBBgwFoAU/Xm2c3jfKKnuQ5hV\n"\
"GyUn+C9RkvIwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiBUenNd\n"\
"fPepPEATlMsCfFI4SfAK33Kp1JkHFt1aG2fmrQIhAOqG1s8s8VjfgdZA1x9NS59B\n"\
"sVBSx9HmnJ/jtn//SRMl\n"\
"-----END CERTIFICATE-----\n"

#endif /* SECURE_KEYS_H_ */

/* [] END OF FILE */
